[toolchain]
anchor_version = "0.29.0"

[features]
seeds = true
skip-lint = false

[programs.devnet]
case_study = "EqtUtzoDUq8fQSdQATey5wJgmZHm4bEpDsKb24vHmPd6"
experience_token = "7mdSmYYPVfGmbnSRQ7kiwXVW9BHnefKRdZ6PJmwt4fga"

[programs.testnet]
case_study = "11111111111111111111111111111111"
experience_token = "7mdSmYYPVfGmbnSRQ7kiwXVW9BHnefKRdZ6PJmwt4fga"

[programs.mainnet]
case_study = "11111111111111111111111111111111"
experience_token = "7mdSmYYPVfGmbnSRQ7kiwXVW9BHnefKRdZ6PJmwt4fga"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
