[package]
name = "experience-token"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.29"
anchor-spl = "0.29"
solana-program = "1.17"
blake3 = "=1.5.5"

[lib]
crate-type = ["cdylib", "lib"]
name = "experience_token"
