[package]
name = "case-study"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.32"
anchor-spl = "0.32"
solana-program = "2.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "case_study"
